development:
  adapter: sqlite3
  database: db/db_development
  timeout: 5000
  
production:
  adapter: sqlite3
  database: db/db_development
  timeout: 5000

test:
  adapter: sqlite3
  database: db/db_development
  timeout: 5000