defaults: &defaults
  username: yourhires
  password: <%= File.exists?('/etc/yourhires_db_passwd') ? File.read('/etc/yourhires_db_passwd') : 'yourhires' %>
  adapter: mysql
  host: localhost
  socket: /tmp/mysql.sock
  database: yourhires_<%= RAILS_ENV %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  username: yourhires
  <<: *defaults